### ISSUE TITLE
Is it possible to separate Custom Logs & System Logs

### ISSUE THREAD

**Issue by nik6018** [WeTransfer/Diagnostics#82]
Hi Guys,

As far as I have tried there is no way to separate the custom log messages which are clubbed together in automatically created logs.

So is it possible to create a separate report for the Custom Logs ? As the **"SYSTEM:"** prefixed logs have too much debug prints from different frameworks that I don't want.

I also tried the filtering for the report, but the logs report is just on big string.

Let me know if I missing something that I haven't tried 😅

**Comment by AvdLee** [comment]
@nik6018 this is currently not possible. I'll mark it as a feature request. Feel free to add this yourself behind a boolean flag, and open a PR accordingly. Happy to review!

**Comment by nik6018** [comment]
@AvdLee  Cool. I have implemented this for my personal project, I'll submit the PR soon :)

**Comment by wetransferplatform** [comment]
The pull request #103 that closed this issue was merged and released as part of [Release 2.0.0](https://github.com/WeTransfer/Diagnostics/releases/tag/2.0.0) :rocket:
Please let us know if the functionality works as expected as a reply here. If it does not, please open a new issue. Thanks!<p align="right"><i>Generated by <a href="https://github.com/WeTransfer/GitBuddy">GitBuddy</a></i></p>
