### ISSUE TITLE
Use MetricKit to better collect crashes

### ISSUE THREAD

**Issue by AvdLee** [WeTransfer/Diagnostics#86]
![IMG_5293](https://user-images.githubusercontent.com/4329185/121858309-c8558100-ccf6-11eb-9476-c3b150c1a4bc.JPG)

**Comment by AvdLee** [comment]
Valuable resources:
- https://www.andyibanez.com/posts/benchmarking-app-metrickit/
- https://franticrock.medium.com/why-is-my-app-getting-killed-wwdc2020-talk-summary-b350d0444fb2
- https://developer.apple.com/documentation/metrickit/mxdiagnosticpayload/3552309-crashdiagnostics
- https://developer.apple.com/documentation/metrickit/mxdiagnosticpayload/3552308-cpuexceptiondiagnostics

This might not be useful in all cases, as the metrics are only reported once every 24 hours.

**Comment by wetransferplatform** [comment]
The pull request #89 that closed this issue was merged and released as part of [Release 1.10.0](https://github.com/WeTransfer/Diagnostics/releases/tag/1.10.0) :rocket:
Please let us know if the functionality works as expected as a reply here. If it does not, please open a new issue. Thanks!<p align="right"><i>Generated by <a href="https://github.com/WeTransfer/GitBuddy">GitBuddy</a></i></p>
