### ISSUE TITLE
[Reports] Make it easier to navigate through sessions

### ISSUE THREAD

**Issue by AvdLee** [WeTransfer/Diagnostics#95]
It would be nice if we can collapse sections and get an easier overview of all the sessions

**Comment by wetransferplatform** [comment]
The pull request #103 that closed this issue was merged and released as part of [Release 2.0.0](https://github.com/WeTransfer/Diagnostics/releases/tag/2.0.0) :rocket:
Please let us know if the functionality works as expected as a reply here. If it does not, please open a new issue. Thanks!<p align="right"><i>Generated by <a href="https://github.com/WeTransfer/GitBuddy">GitBuddy</a></i></p>
