### ISSUE TITLE
[Reports] Filter easily on errors

### ISSUE THREAD

**Issue by AvdLee** [WeTransfer/Diagnostics#96]
This way, it should be easier to predict what's going wrong for the user

**Comment by wetransferplatform** [comment]
The pull request #103 that closed this issue was merged and released as part of [Release 2.0.0](https://github.com/WeTransfer/Diagnostics/releases/tag/2.0.0) :rocket:
Please let us know if the functionality works as expected as a reply here. If it does not, please open a new issue. Thanks!<p align="right"><i>Generated by <a href="https://github.com/WeTransfer/GitBuddy">GitBuddy</a></i></p>
