### ISSUE TITLE
[Reports] Smart reporting

### ISSUE THREAD

**Issue by AvdLee** [WeTransfer/Diagnostics#97]
be smart about reporting what is likely happening. E.g.: “This might be caused because the user user was low on storage” or “This error happened in the user’s latest session: ”

Ideas for Transfer apps:
- [ ] this might be a stretch, but is it possible to be able to see if the user closed the app during upload? or just closed/exited it at all?
- [ ] Upload failure reasons

**Comment by AvdLee** [comment]
https://wetransfer.atlassian.net/browse/TMI-30?atlOrigin=eyJpIjoiMTEwZWJlZGZjMjBhNDFjMDg2Y2E2Yzc5NzY2MGM0YjkiLCJwIjoiaiJ9

**Comment by wetransferplatform** [comment]
The pull request #113 that closed this issue was merged and released as part of [Release 3.0.0](https://github.com/WeTransfer/Diagnostics/releases/tag/3.0.0) :rocket:
Please let us know if the functionality works as expected as a reply here. If it does not, please open a new issue. Thanks!<p align="right"><i>Generated by <a href="https://github.com/WeTransfer/GitBuddy">GitBuddy</a></i></p>
